services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
    volumes:    
      - type: bind
        source: ./luwrain-src
        target: /var/jenkins_home/workspace/testjobs/
volumes: 
  src:

